#!/usr/bin/env bash

usage()
{
    echo "usage: clear_notebooks [-h] "
}

while [ -n "$1" ]; do
    case $1 in
        -h | --help )           usage
                                exit
                                ;;
        * )                     echo "ERROR: Unknown option $1"
                                usage
                                exit 1
                                ;;
    esac
    shift
done

full_path=$(realpath $0)
script_path=$(dirname $full_path)
repo_path=$(dirname $script_path)

for f in `find $repo_path/notebooks -not -path "*/.ipynb_checkpoints/*" -type f -name '*.ipynb'`;
do
  jupyter nbconvert --NbConvertApp.use_output_suffix=False \
                    --NbConvertApp.export_format=notebook \
                    --FilesWriter.build_directory= \
                    --ClearOutputPreprocessor.enabled=True \
                    --ClearOutputPreprocessor.remove_metadata_fields={} \
                    $f
done


