name: Test stable release (conda)

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main", "release"]
  push:
    branches: ["main"] # this also gets called by deploy on push into release

env:
  HDF5_MPI: "ON"
  HDF5_DIR: "/usr/local/"
  DISPLAY: ":99.0"
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    env:
      PYVISTA_OFF_SCREEN: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v6

      - name: Install apt dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt update && sudo apt install -y xvfb

      - uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: fenics-sz
          environment-file: conda/environment.yml
          channel-priority: strict
          auto-update-conda: true
          miniconda-version: "latest"
      
      - run: |
          conda info
          conda list
      
      - name: Initialize
        run: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            python3 -c "from pyvista import start_xvfb;
            try:
              start_xvfb(0.1)
            except:
              pass"
      
      - name: Check package modules import cleanly
        run: bin/check_imports

      - name: Check scripts are up to date
        working-directory: notebooks
        run: |
            ../bin/update_python
            git diff --exit-code || { retcode=$?; echo "Python scripts not up to date with notebook files.  Please update."; exit $retcode; }

      - name: Check notebooks are clean
        working-directory: notebooks
        run: |
            ../bin/clear_notebooks
            git diff --exit-code || { retcode=$?; echo "Jupyter notebooks are not clear.  Please clear output."; exit $retcode; }

      - name: Test background
        working-directory: notebooks/02_background
        run: |
            jupyter execute 2.2b_poisson_1d.ipynb
            jupyter execute 2.3d_poisson_2d_parallel.ipynb
            jupyter execute 2.4e_batchelor_nest_parallel.ipynb
            jupyter execute 2.5b_blankenbach.ipynb

      - name: Test sz_problems
        working-directory: notebooks/03_sz_problems
        run: |
            jupyter execute 3.4b_sz_benchmark.ipynb

      - name: Install package
        working-directory: python
        run: pip install -e .

      - name: Test background scripts
        working-directory: scripts/background
        run: |
            python3 poisson_2d.py 128 -o poisson_2d.bp
            mpiexec -n 2 python3 poisson_2d.py 128 -o poisson_2d_mpi.bp
            python3 poisson_2d.py 128 -t
            mpiexec -n 2 python3 poisson_2d.py 128 -t
            python3 batchelor_nest.py 128 -o batchelor_nest.bp
            mpiexec -n 2 python3 batchelor_nest.py 128 -o batchelor_nest_mpi.bp
            python3 batchelor_nest.py 128 -t
            mpiexec -n 2 python3 batchelor_nest.py 128 -t 

      - name: Test sz_problems scripts
        working-directory: scripts/sz_problems
        run: |
            python3 sz_benchmark.py 1 2 -o sz_benchmark_1.bp
            mpiexec -n 2 python3 sz_benchmark.py 1 2 -o sz_benchmark_1_mpi.bp
            python3 sz_benchmark.py 1 2 -t
            mpiexec -n 2 python3 sz_benchmark.py 1 2 -t
            python3 sz_benchmark.py 2 2 -o sz_benchmark_2.bp
            mpiexec -n 2 python3 sz_benchmark.py 2 2 -o sz_benchmark_2_mpi.bp
            python3 sz_benchmark.py 2 2 -t
            mpiexec -n 2 python3 sz_benchmark.py 2 2 -t

      - name: Test global_suites scripts
        working-directory: scripts/global_suites
        run: |
            python3 sz_suite_ss.py 02_Alaska 3 -o 02_Alaska_ss.bp
            mpiexec -n 2 python3 sz_suite_ss.py 32_Solomon 3 -o 32_Solomon_ss_mpi.bp
            python3 sz_suite_td.py 05_Mexico 3 3 -o 05_Mexico_td.bp
            mpiexec -n 2 python3 sz_suite_td.py 19_N_Antilles 3 3 -o 19_N_Antilles_td_mpi.bp

